monthly_income = input("Enter your monthly income: ")
monthly_expences = input("Enter your monthly expenses: ")
savings = int(monthly_income) - int(monthly_expences)
projected_savings = savings * 12 + (savings * 0.05 * 12)
print("Your monthly savings are:$", savings)
print("Projected savings after one year, with interest is:$", projected_savings)