monthly_income = input("Enter your monthly income: ")
monthly_expences = input("Enter your monthly expenses: ")
monthly_savings = int(monthly_income) - int(monthly_expences)
projected_savings = monthly_savings * 12 + (monthly_savings * 0.05 * 12)
print("Your monthly savings are:$", monthly_savings)
print("Projected savings after one year, with interest is:$", projected_savings)